# Yaml is white-space sensitive (use 2 spaces to indent).

###
# Settings to apply to all windows.
#
# Docs regarding global: https://some-future-docs-link.com
global:
  # Whether to enable the browser devtools.
  enable_devtools: false

###
# Define a new window with an id of 'bar'. This window can then be opened
# via the Zebar cli by running 'zebar open bar'.
#
# Docs regarding window: https://some-future-docs-link.com
window/bar:
  providers: ["self"]
  # Width of the window in physical pixels.
  width: "{{ self.args.MONITOR_WIDTH }}"
  # Height of the window in physical pixels.
  height: "42"
  # X-position of the window in physical pixels.
  position_x: "{{ self.args.MONITOR_X }}"
  # Y-position of the window in physical pixels.
  position_y: "{{ self.args.MONITOR_Y }}"
  # Whether to show the window above/below all others.
  # Allowed values: 'always_on_top', 'always_on_bottom', 'normal'.
  z_order: "always_on_bottom"
  # Whether the window should be shown in the taskbar.
  show_in_taskbar: false
  # Whether the window should have resize handles.
  resizable: false
  # Styles to apply globally within the window. For example, we can use
  # this to import the Nerdfonts icon font. Ref https://www.nerdfonts.com/cheat-sheet
  # for a cheatsheet of available Nerdfonts icons.
  # global_styles: |
  # @import "https://www.nerdfonts.com/assets/css/webfont.css";
  # CSS/SCSS styles to apply to the root element within the window.
  styles: |
    display: grid;
    grid-template-columns: 1fr 1fr 1fr;
    align-items: center;
    height: 100%;
    color: #fdf9f3;
    font-family: 'CaskaydiaMono Nerd Font Mono';
    font-size: 13.5pt;
    padding: 0px 24px 0px;
    border: 0px solid #fdf9f3;
    background: #221f22E6;
  group/left:
    styles: |
      display: flex;
      align-items: center;

    template/logo:
      styles: |
        margin-right: 20px;

        .os {
          font-size: 32px;
          color: #ff6188;
        }
      template: |
        <div class='os'></div>

    template/workspaces:
      styles: |
        display: flex;
        align-items: center;

        .workspace {
          background: rgba(255, 255, 255, 0.05);
          margin-right: 4px;
          width: 30px;
          height: 30px;
          color: #ffffffe6;
          border: none;
          border-radius: 2px;

          &.active {
            background: rgba(255, 255, 255, 0.1);
          }
        }
      providers: ["komorebi"]
      template: |
        @for (workspace of komorebi.currentWorkspaces) {
          <button class="workspace {{ workspace === komorebi.focusedWorkspace && 'active' }}">
            {{ workspace.name }}
          </button>
        }

  group/center:
    styles: |
      justify-self: center;

    template/host:
      providers: ["host"]
      template: |
        <span>{{host.hostname}}</span>

  group/right:
    styles: |
      justify-self: end;
      align-items: center;
      display: flex;

      .template {
        margin-left: 24px;
      }

    template/cpu:
      providers:
        - type: 'cpu'
          refresh_interval: 1000
      styles: |
        position: relative;
        margin-right: 32px;

        .cpu {
          position: absolute;
          left: -24px;
          top: -8px;
          font-size: 24pt;
          color: #ff6188;
        }
      template: |
        <span class='cpu'></span><span>{{ Math.round(cpu.usage) }}%</span>

    template/memory:
      providers:
        - type: 'memory'
          refresh_interval: 1000
      styles: |
        position: relative;
        margin-right: 21px;

        .memory {
          position: absolute;
          left: -30px;
          top: -11px;
          font-size: 28pt;
          color: #a9dc76;
        }
      template: |
        <div class='memory'></div>
        {{ ((usedBytes, totalBytes) => {
            return `${(usedBytes / (1024 * 1024 * 1024)).toFixed(2).toLocaleString() + ' GB'}`;
        })(memory.usedMemory, memory.totalMemory) }}

    template/battery:
      providers: ["battery"]
      styles: |
        position: relative;
        margin-right: 28px;

        .battery {
          position: absolute;
          left: -20px;
          top: -3px;
          font-size: 16pt;
          color: #ffd866;
        }

        .low-battery {
          color: #ff6188;
        }

        .charging-icon {
          color: #78dce8;
          position: absolute;
          z-index: 5;
          font-size: 15pt;
          left: -12px;
          bottom: -8px;
        }

        .full {
          position: absolute;
          z-index: 5;
          color: #a9dc76;
          font-size: 11pt;
          left: -14px;
          bottom: 0px;
        }
      template: |
        <!-- Show icon for whether battery is charging. -->
        @if (battery.state === 'charging') {<div class="charging-icon">󱐋</div>}
        @else if (battery.state === 'full') {<div class="charging-icon full">✔</div>}

        <!-- Show icon for how much of the battery is charged. -->
        @if (battery.chargePercent > 94) {<div class='battery'>󰁹 </div>}
        @else if (battery.chargePercent > 80) {<div class='battery'>󰂂 </div>}
        @else if (battery.chargePercent > 70) {<div class='battery'>󰂁 </div>}
        @else if (battery.chargePercent > 60) {<div class='battery'>󰂀 </div>}
        @else if (battery.chargePercent > 50) {<div class='battery'>󰁿 </div>}
        @else if (battery.chargePercent > 30) {<div class='battery'>󰁾 </div>}
        @else if (battery.chargePercent > 20) {<div class='battery'>󰁽 </div>}
        @else {<div class='battery'>󰁺 </div>}

        {{ Math.round(battery.chargePercent) }}%

    template/weather:
      providers: ["weather"]
      styles: |
        position: relative;
        margin-right: 22px;

        span {
          position: absolute;
          font-size: 21pt;
          left: -30px;
          top: -3px;
        }
        .clear-day {
          color: #ffd866;
        }
        .cloudy-day {
          color: #fdf9f3;
        }
        .rainy-day {
          font-size: 32pt;
          left: -28px;
          top: -16px;
          color: #59c6ff;
        }
      template: |
        @switch (weather.status) {
          @case ('clear_day') {<span class='clear-day'>☀ </span>}
          @case ('clear_night') {<span class='clear-day'> </span>}
          @case ('cloudy_day') {<span class='cloudy-day'>☁ </span>}
          @case ('cloudy_night') {<span class='cloudy-day'>☁ </span>}
          @case ('light_rain_day') {<span class='rainy-day'> </span>}
          @case ('light_rain_night') {<span class='rainy-day'> </span>}
          @case ('heavy_rain_day') {<span class='rainy-day'> </span>}
          @case ('heavy_rain_night') {<span class='rainy-day'> </span>}
          @case ('snow_day') {<span class='cloudy-day'> </span>}
          @case ('snow_night') {<span class='cloudy-day'> </span>}
          @case ('thunder_day') {<span class='rainy-day'> </span>}
          @case ('thunder_night') {<span class='rainy-day'> </span>}
        }
        {{ weather.celsiusTemp }}°C

    template/clock:
      providers: ["date"]
      # Available date tokens: https://moment.github.io/luxon/#/formatting?id=table-of-tokens
      styles: |
        position: relative;

        .clock {
          color: #ab9df2;
          position: absolute;
          font-size: 21pt;
          left: -23px;
          top: -6px;
        }
      template: |
        <span class='clock'>󰥔</span>{{ date.toFormat(date.now, 't, EEEE, d MMM y') }}
