# Yaml is white-space sensitive (use 2 spaces to indent).

###
# Settings to apply to all windows.
#
# Docs regarding global: https://some-future-docs-link.com
global:
  # Whether to enable the browser devtools.
  enable_devtools: false

###
# Define a new window with an id of 'bar'. This window can then be opened
# via the Zebar cli by running 'zebar open bar'.
#
# Docs regarding window: https://some-future-docs-link.com
window/bar:
  providers: ["self"]
  # Width of the window in physical pixels.
  width: "{{ self.args.MONITOR_WIDTH - 24 }}"
  # Height of the window in physical pixels.
  height: "42"
  # X-position of the window in physical pixels.
  position_x: "{{ self.args.MONITOR_X + 12 }}"
  # Y-position of the window in physical pixels.
  position_y: "{{ self.args.MONITOR_Y + 12 }}"
  # Whether to show the window above/below all others.
  # Allowed values: 'always_on_top', 'always_on_bottom', 'normal'.
  z_order: "always_on_bottom"
  # Whether the window should be shown in the taskbar.
  show_in_taskbar: false
  # Whether the window should have resize handles.
  resizable: false
  # Styles to apply globally within the window. For example, we can use
  # this to import the Nerdfonts icon font. Ref https://www.nerdfonts.com/cheat-sheet
  # for a cheatsheet of available Nerdfonts icons.
  # global_styles: |
  # @import "https://www.nerdfonts.com/assets/css/webfont.css";
  # CSS/SCSS styles to apply to the root element within the window.
  styles: |
    display: grid;
    grid-template-columns: 1fr 1fr 1fr;
    align-items: center;
    height: 100%;
    color: #A599E9;
    font-family: 'DM Mono Regular', 'CaskaydiaMono Nerd Font Mono';
    font-size: 14pt;
    padding: 0px 24px 0px;
    border: 0px solid #000000;
    background: #1E1E3FCC;
  group/left:
    styles: |
      display: flex;
      align-items: center;

    template/logo:
      styles: |
        margin-right: 20px;

        .os {
          font-size: 32px;
          color: #4D21FC;
        }
      template: |
        <div class='os'></div>

    template/host:
      providers:
        - type: 'host'
          refresh_interval: 60000
      template: |
        <span>{{host.hostname}}</span>

  group/center:
    styles: |
      justify-self: center;

    template/workspaces:
      styles: |
        display: flex;
        align-items: center;

        .workspace {
          background: rgba(255, 255, 255, 0.00);

          margin-right: 4px;
          color: #A599E9;
          border: none;
          border-radius: 2px;
          width: 32px;
          font-size: 24px;
          opacity: 30%;
        }

        .have-windows {
          font-size: 32px;
          opacity: 100%;
        }

        .active {
          font-size: 32px;
          color: #FFEE80;
          opacity: 100%;
        }
      providers: ["komorebi"]
      template: |
        @for (workspace of komorebi.currentWorkspaces) {
          <button class="workspace {{ workspace.tilingContainers.length && 'have-windows ' }} - {{ workspace === komorebi.focusedWorkspace && 'active ' }}">
            {{ workspace === komorebi.focusedWorkspace ? '󰫢' : '' }}
          </button>
        }

  group/right:
    styles: |
      justify-self: end;
      align-items: center;
      display: flex;

      .template {
        margin-left: 24px;
      }

    template/cpu:
      providers:
        - type: "cpu"
          refresh_interval: 1000
      styles: |
        position: relative;
        margin-right: 32px;

        .cpu {
          position: absolute;
          left: -24px;
          top: -8px;
          font-size: 24pt;
          color: #FF628C;
        }
      template: |
        <span class='cpu'></span><span>{{ Math.round(cpu.usage) }}%</span>

    template/memory:
      providers:
        - type: "memory"
          refresh_interval: 1000
      styles: |
        position: relative;
        margin-right: 21px;

        .memory {
          position: absolute;
          left: -28px;
          top: -10px;
          font-size: 28pt;
          color: #A5FF90;
        }
      template: |
        <div class='memory'></div>
        {{ ((usedBytes, totalBytes) => {
            return `${(usedBytes / (1024 * 1024 * 1024)).toFixed(2).toLocaleString() + ' GiB'}`;
        })(memory.usedMemory, memory.totalMemory) }}

    template/battery:
      providers: ["battery"]
      styles: |
        position: relative;
        margin-right: 28px;

        .battery {
          position: absolute;
          left: -20px;
          top: -1px;
          font-size: 14pt;
          color: #FFEE80;
        }

        .low-battery {
          color: #FF628C;
        }

        .charging-icon {
          color: #9EFFFF;
          position: absolute;
          z-index: 5;
          font-size: 15pt;
          left: -14px;
          bottom: -2px;
          filter:
            drop-shadow( 1px  0px 0px #1d1f21)
            drop-shadow(-1px  0px 0px #1d1f21)
            drop-shadow( 0px  1px 0px #1d1f21)
            drop-shadow( 0px -1px 0px #1d1f21);
        }

        .full {
          position: absolute;
          z-index: 5;
          color: #A5FF90;
          font-size: 11pt;
          left: -14px;
          bottom: 0px;
        }
      template: |
        <!-- Show icon for whether battery is charging. -->
        @if (battery.state === 'charging') {<div class="charging-icon">󱐋</div>}
        @else if (battery.state === 'full') {<div class="charging-icon full">✔</div>}

        <!-- Show icon for how much of the battery is charged. -->
        @if (battery.chargePercent > 94) {<div class='battery'>󰁹 </div>}
        @else if (battery.chargePercent > 80) {<div class='battery'>󰂂 </div>}
        @else if (battery.chargePercent > 70) {<div class='battery'>󰂁 </div>}
        @else if (battery.chargePercent > 60) {<div class='battery'>󰂀 </div>}
        @else if (battery.chargePercent > 50) {<div class='battery'>󰁿 </div>}
        @else if (battery.chargePercent > 30) {<div class='battery'>󰁾 </div>}
        @else if (battery.chargePercent > 20) {<div class='battery'>󰁽 </div>}
        @else {<div class='battery'>󰁺 </div>}

        {{ Math.round(battery.chargePercent) }}%

    # template/network:
    #   providers: ["komorebi"]
    #   template: |
    #     {{ JSON.stringify(komorebi.currentWorkspaces) }}

    template/weather:
      providers: ["weather"]
      styles: |
        position: relative;
        margin-right: 22px;

        span {
          position: absolute;
          font-size: 28pt;
          left: -26px;
          top: -10px;
        }
        .clear-day {
          color: #FFEE80;
        }
        .cloudy-day {
          color: #E1EFFF;
        }
        .rainy-day {
          color: #9EFFFF;
        }
      template: |
        @switch (weather.status) {
          @case ('clear_day') {<span class='clear-day'> </span>}
          @case ('clear_night') {<span class='clear-day'> </span>}
          @case ('cloudy_day') {<span class='cloudy-day'> </span>}
          @case ('cloudy_night') {<span class='cloudy-day'> </span>}
          @case ('light_rain_day') {<span class='rainy-day'> </span>}
          @case ('light_rain_night') {<span class='rainy-day'> </span>}
          @case ('heavy_rain_day') {<span class='rainy-day'> </span>}
          @case ('heavy_rain_night') {<span class='rainy-day'> </span>}
          @case ('snow_day') {<span class='cloudy-day'>☃ </span>}
          @case ('snow_night') {<span class='cloudy-day'>☃ </span>}
          @case ('thunder_day') {<span class='rainy-day'> </span>}
          @case ('thunder_night') {<span class='rainy-day'> </span>}
        }
        {{ weather.celsiusTemp }}°c

    template/clock:
      providers: ["date"]
      # Available date tokens: https://moment.github.io/luxon/#/formatting?id=table-of-tokens
      styles: |
        position: relative;

        .clock {
          color: #B362FF;
          position: absolute;
          font-size: 22pt;
          left: -23px;
          top: -6px;
        }
      template: |
        <span class='clock'>󰥔</span>{{ date.toFormat(date.now, 't, EEEE, d MMM y') }}
